### PR TITLE
Fix documentation of ruleRepetition option

### PR DESCRIPTION
**Pull request by vweevers**
To match:

https://github.com/syntax-tree/mdast-util-to-markdown/blob/5fa790ee4cdead2a6c11b6a6f73c59eb0f9ca295/lib/util/check-rule-repeat.js#L4

### CODE REVIEW

**Review by ChristianMurphy — APPROVED** [review]
Looks good, it also would need to be updated here:
https://github.com/syntax-tree/mdast-util-to-markdown/blob/5fa790ee4cdead2a6c11b6a6f73c59eb0f9ca295/types/index.d.ts#L74

**Comment by wooorm** [comment]
Thanks, weird! Seems `ruleRepeat` is also incorrectly in the types, could you update that too?

**Comment by wooorm** [comment]
Not sure how this happened 😅 It’s not in any of the other projects

**Review by wooorm — APPROVED** [review]

**Comment by wooorm** [comment]
Thanks Vincent, released!

**Pull request merged**
