### PR TITLE
invalid: pretty error message

### PR DESCRIPTION
**Pull request by milahu**
### Initial checklist

*   [ ] I read the support docs 
*   [ ] I read the contributing guide 
*   [ ] I agree to follow the code of conduct 
*   [ ] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [ ] If applicable, I’ve added docs and tests

### Description of changes

help with debugging of user errors

before

```
Error: Cannot handle value `[object Object],[object Object]`, expected node
```

after

```
Error: Cannot handle value, expected node. value:
[
  {
    "type": "html",
    "value": "#### attrPath\n"
  },
  [
    {
      "type": "html",
      "value": "A list of strings representing the path through the nested attribute set set.\n"
    }
  ]
]
```

todo: refactor, also use for `function unknown(node)`

### CODE REVIEW

**Comment by wooorm** [comment]
I’m open to improving this error message.
I’m not sure dumping JSON really clarifies things though.

From your example, I really don’t get how you’re getting HTML nodes with those values btw? That seems like a rather big problem somewhere else?

**Comment by milahu** [comment]
> I really don’t get how you’re getting HTML nodes with those values btw?

user error on my side

bad:

```js
return [
  h(node, 'html', 'hello'),
  h(node, 'html', 'world'),
]
```

good:

```js
return h(node, 'html', [
  h(node, 'html', 'hello'),
  h(node, 'html', 'world'),
])
```

the `[object Object],[object Object]` message was not helpful to find this error

**Comment by ChristianMurphy** [comment]
A few things worth noting here:
1. Please fill in the issue template
2. I'm a bit unclear how this improves the error messaging in the example you provide, it would show the content but wouldn't offer any more info on why.
3. This could get rather massive in real documents 
4. This is also covered by typescript typings

**Comment by milahu** [comment]
> This could get rather massive in real documents

solutions:

console.dir before throw

stringify with limited width + depth
https://github.com/BridgeAR/safe-stable-stringify

**Comment by ChristianMurphy** [comment]
> > I'm a bit unclear how this improves the error messaging in the example you provide, it would show the content but wouldn't offer any more info on why.
>
> i dont want to use a debugger (or insert console.dir) just to find such a bug.

I agree, and that is precisely my point.
Printing the contents alone would not help.
It would cause clutter without explaining to the root of the issue.
And would make searching stackoverflow even harder given all the clutter.

An alternative would be changing the error messaging to something more explanatory. E.G. "an array was passed where a node object is expected", and providing a reference to find the root of the issue, like a JSON path to the parent node.

**Comment by milahu** [comment]
> and providing a reference to find the root of the issue, like a JSON path to the parent node.

yes please : )

**Comment by wooorm** [comment]
> user error on my side

User error in which project?

> message was not helpful to find this error

I don’t think this project can do much about making your error “pretty”.
The problem is much earlier.
At this point, the value can be anything.
I agree with Christian that printing the value as JSON will get verbose and will likely not help many users.
I am also not sure about imposing the package size of `safe-stable-stringify` or similar on each user of this project.
But, if the problem is in an earlier project, perhaps an error there can be of use.

> (iirc, the error stack was not useful)

Can you share the stack?

> like a JSON path to the parent node.

It’s an interesting idea but I am not sure that `tree.children[5].children[4].children[3].children` or so will shed the desired light?

---

@milahu can you:
a) please fill out the issue template
b) please share more about what you are doing here? Actual code, dependencies, versions, stack traces

Finally, there are some other problems in the few example I see, such as: `html` nodes are abused for arbitrary strings instead of HTML, and that a `html` node in your “good” example has children. These things will surface as problems in several utilities and plugins. Please don’t use them.

**Comment by milahu** [comment]
let me describe this in prose, as i have wasted enough hours on this ...

`invalid` is called when i produce a markdown tree like

```js
{
  type: 'root',
  children: [
    'bad'
  ]
}
```

instead, i should do

```js
{
  type: 'root',
  children: [
    {
      type: 'text',
      value: 'good'
    }
  ]
}
```

my original error

<blockquote>

```
Error: Cannot handle value `[object Object],[object Object]`, expected node
```

</blockquote>

is caused when i forget the array-destructuring of child nodes

```js
{
  type: 'root',
  children: [
    {
      type: 'text',
      value: 'good'
    },
    // ...[ // good
    [ // bad
      {
        type: 'text',
        value: 'asdf'
      },
      {
        type: 'text',
        value: 'asdf'
      },
    ]
  ]
}
```

fixed by adding `...` before the array

i would just `console.dir(value)` before `throw`, as this is a rare internal error

**Comment by milahu** [comment]
> Actual code

your wish has been granted ; )

```sh
cd $(mktemp -d)
npm init -y
pnpm install mdast-util-to-markdown

cat >test.mjs <<'EOF'
import {toMarkdown} from 'mdast-util-to-markdown'

console.log(toMarkdown({

type: "root",

children: [

// good
{ type: "heading", children: [ { type: "text", value: "hello" } ]},

// bad: string instead of text node
// TypeError: Cannot use 'in' operator to search for 'value' in hello
//{ type: "heading", children: [ "hello" ]},

// good
{ type: "list", children: [
{ type: "listItem", children: [ { type: "text", value: "hello" } ] },
...[
  { type: "listItem", children: [ { type: "text", value: "hello" } ] },
],
]},

// bad: forget the array-destructuring of child nodes
// Error: Cannot handle value `[object Object]`, expected node
{ type: "list", children: [
[
  { type: "listItem", children: [ { type: "text", value: "hello" } ] },
],
]},


]

}))

EOF

node test.mjs
```

**Comment by wooorm** [comment]
Thanks but this seems very different from the code here? https://github.com/syntax-tree/mdast-util-to-markdown/pull/55#issuecomment-1281361794. I am wondering what that code is. What is `h`...

**Comment by milahu** [comment]
thats in a custom handler in

https://github.com/syntax-tree/hast-util-to-mdast/tree/main/lib/handlers

and later in the unifiedjs chain
the "bad" ast is passed to mdast-util-to-markdown

**Comment by wooorm** [comment]
Thanks. This helps get closer to your problem. Unfortunately, I cannot reproduce your problem. That project accepts arrays as return values.
Here’s the code for that: https://github.com/syntax-tree/hast-util-to-mdast/blob/ae8239ecdf6e87ff710bb5c0817731e5ed382f26/lib/all.js.
Here’s a reproduction:

```js
import {parseFragment} from 'parse5'
import {fromParse5} from 'hast-util-from-parse5'
import {toMdast} from './index.js'
import {toMarkdown} from 'mdast-util-to-markdown'

const html = '<h1>asd</h1>'
const parse5 = parseFragment(html)
const hast = fromParse5(parse5)
const mdast = toMdast(hast, {
  handlers: {
    h1() {
      return [
        {type: 'text', value: 'a'},
        {type: 'text', value: 'b'}
      ]
    }
  }
})
const markdown = toMarkdown(mdast)

console.log(markdown)
```

Also the following work:

```js
    h1() {
      return [
        {type: 'html', value: 'a'},
        {type: 'html', value: 'b'}
      ]
    }
```

```js
    h1(h, node) {
      return [
        h(node, 'html', 'a'),
        h(node, 'html', 'b'),
      ]
    }
```

I would really appreciate it if you can share actual code that you were using with some packages that eventually resulted in this deep-down error.

**Comment by milahu** [comment]
found it 

https://github.com/milahu/unifiedjs-docbook/blob/6634fce2600361f6bc824a054080d0187e2181ec/packages/to-markdown-util/lib/handlers/docbook/index.js#L414

```js
docbookHandlers['example'] = (h, node) => {
  const title = node.children.find(
    (child) => ('name' in child && child.name == 'title')
  )
  const result = [
    h(node, 'heading', {depth: 4}, [
      // repro for Error: Cannot handle value `[object Object]`, expected node
      // bad
      all(h, title),
      // good
      //...all(h, title),
    ]),
  ]
  return result
}
```

this works in other places, where i return an array directly, like in your example

https://github.com/milahu/unifiedjs-docbook/blob/6634fce2600361f6bc824a054080d0187e2181ec/packages/to-markdown-util/lib/handlers/docbook/index.js#L371

**Comment by wooorm** [comment]
Thanks @milahu for the actual reproduction! Helps a lot in my understanding. I appreciate that you spend the time to dig that back up!

Unfortunately I read your earlier code different from this one. I thought we could perhaps throw an earlier error there, with a good stack trace. But if this is it, we can’t: the project assumes you pass valid children and doesn’t check each value.

I’m personally not in favor of checking all the children in `hast-util-to-mdast`. That would slow everyone down.
I don’t think adding a `console.log` here will help much either, and has some drawbacks as laid out above.
I’m open, but personally not strongly in favor of, adding a node path (like Christian suggested in https://github.com/syntax-tree/mdast-util-to-markdown/pull/55#issuecomment-1282261592). I don’t think it would’ve helped you here, and I too believe the performance loss in adding it will weigh on everyone, and I personally don’t think the trade off is worth it. @ChristianMurphy WDYT?

**Comment by milahu** [comment]
> I don’t think adding a `console.log` here will help much either, and has some drawbacks as laid out above.

`console.error` aka printing to stderr? zero overhead for the happy path

**Comment by wooorm** [comment]
> zero overhead for the happy path

See my comment above:

> I don’t think it’s a good idea to hardcode `console.*` in open source libraries though. `console` isn‘t always available. `console` goes to STDIN instead of STDERR (which this should perhaps to). `console` often doesn’t get tracked at all.

**Comment by ChristianMurphy** [comment]
>  I don’t think it would’ve helped you here, and I too believe the performance loss in adding it will weigh on everyone, and I personally don’t think the trade off is worth it. @ChristianMurphy WDYT?

I don't feel strongly on it.
If there would be a significant performance loss I'd lean against it.

Something which may be worth noting again here.
All of the packages and node/mdast interfaces mentioned here are strongly typed with TypeScript.
Those typings can catch many typos/input issues, I think it would be able to catch the issues mentioned here as well.

The typings can be leveraged both in TypeScript `.ts` files and in JavaScript `.js` with JSDoc comments.
Most of unified uses JS with JSDoc for TypeScript, with the following config:
https://github.com/syntax-tree/mdast-util-to-markdown/blob/c47743b7ef393d33bb463f66d735815b77a6cda8/tsconfig.json#L1-L16

and runs the type checks with:

https://github.com/syntax-tree/mdast-util-to-markdown/blob/c47743b7ef393d33bb463f66d735815b77a6cda8/package.json#L64

Which allows detecting issues without adding runtime overhead, getting feedback on specifically where the issue is coming from in the file, and clear error messages (most of the time, and getting better).

**Comment by wooorm** [comment]
Yep, I’d also say that types and tests should catch all of this.
I get that it’s a confusing error, but there’s not much this project can do about it. The problem was made much earlier. Types indeed catch that. And test-driven development will also catch it pretty quickly.

If we’re not feeling strongly about it, and there are good alternative solutions, I think I’d want to close this.

**Comment by wooorm** [comment]
Closing, as there don’t seem good (small code size with improved results) solutions to this issue. Thanks everyone for the discussion!

**Pull request closed without merging**
